workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 45
    environment:
      vars:
        PACKAGE_NAME: "com.exaquiz.app"
      node: 16.13.1
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
